### ISSUE TITLE
Developer console crash report: android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-android#36]
The following crash report appears in the Google play store developer console: android.os.TransactionTooLargeException in android.os.BinderProxy.transactNative
```
Package Name,Crash Report Date And Time,Crash Report Millis Since Epoch,Device,Android OS Version,App Version Name,App Version Code,Exception Class Name,Exception Message,Throwing File Name,Throwing Class Name,Throwing Method Name,Throwing Line Number,Native Crash Library,Native Crash Location
org.tiqr.authenticator,2017-03-16T15:10:14Z,1489677014998,trlte,23,2.6,8,android.os.TransactionTooLargeException,data parcel size 2623372 bytes,Binder.java,android.os.BinderProxy,transactNative,-2,,
org.tiqr.authenticator,2017-03-16T15:26:06Z,1489677966106,trlte,23,2.6,8,android.os.TransactionTooLargeException,data parcel size 2623376 bytes,Binder.java,android.os.BinderProxy,transactNative,-2,,
org.tiqr.authenticator,2017-03-16T15:58:36Z,1489679916658,trlte,23,2.6,8,android.os.TransactionTooLargeException,data parcel size 2623384 bytes,Binder.java,android.os.BinderProxy,transactNative,-2,,
org.tiqr.authenticator,2017-03-17T16:53:54Z,1489769634886,trlte,23,2.6,8,android.os.TransactionTooLargeException,data parcel size 2623372 bytes,Binder.java,android.os.BinderProxy,transactNative,-2,,
```
Application version: 8
Android version: Android 6.0
Device: Galaxy Note4 (trlte)
Manufacturer: Samsung
Android version: Android 4.4 
RAM (MB) 3072 
Screen size 1440 × 2560 
Screen density (dpi) 640 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm CPU model APQ8084
```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1547)
	at android.app.Activity.startActivityForResult(Activity.java:4283)
	at android.app.Activity.startActivityForResult(Activity.java:4230)
	at android.app.Activity.startActivity(Activity.java:4567)
	at android.app.Activity.startActivity(Activity.java:4535)
	at org.tiqr.authenticator.qr.CaptureActivity$3.onParseEnrollmentChallengeSuccess(CaptureActivity.java:277)
	at org.tiqr.service.enrollment.EnrollmentService$1.onPostExecute(EnrollmentService.java:132)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.os.TransactionTooLargeException: data parcel size 2623376 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:503)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3130)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1540)
	... 15 more
```

**Comment by ijansch** [comment]
Closing this issue, pull is already merged.
